# Generated by Django 5.0.2 on 2024-02-29 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('meaning', models.CharField(max_length=10000)),
                ('pronunciation', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'words',
            },
        ),
    ]
