# Generated by Django 5.0.2 on 2024-02-29 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_words_user'),
        ('users', '0002_alter_users_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='words',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.users', to_field='user_name'),
        ),
    ]
