# Generated by Django 5.0.2 on 2024-02-29 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_words_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='words',
            name='pronunciation',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
